export function planPulse() {
  return [
    {
      id: 'task-scaffold',
      title: 'Scaffold the Pulse package',
      kind: 'write',
      priority: 10,
      paths: ['forge/package.json', 'forge/README.md'],
      deps: [],
      spec: { files: { 'forge/package.json': 'package.json', 'forge/README.md': 'README.md' } },
    },
    {
      id: 'task-domain',
      title: 'Write Pulse domain rules',
      kind: 'write',
      priority: 20,
      paths: ['forge/src/domain.mjs'],
      deps: [],
      spec: { files: { 'forge/src/domain.mjs': 'src/domain.mjs' } },
    },
    {
      id: 'task-domain-test',
      title: 'Verify domain invariants',
      kind: 'test',
      priority: 30,
      paths: ['forge/test/domain.test.mjs'],
      deps: ['task-domain'],
      spec: {
        files: { 'forge/test/domain.test.mjs': 'test/domain.test.mjs' },
        run: ['--test', 'forge/test/domain.test.mjs'],
      },
    },
    {
      id: 'task-store',
      title: 'Write durable Pulse store',
      kind: 'write',
      priority: 40,
      paths: ['forge/src/store.mjs'],
      deps: ['task-domain'],
      spec: {
        files: { 'forge/src/store.mjs': 'src/store.mjs' },
        buggyFiles: { 'forge/src/store.mjs': 'src/store.buggy.mjs' },
        buggyUntilAttempt: 1,
      },
    },
    {
      id: 'task-store-test',
      title: 'Verify store persistence',
      kind: 'test',
      priority: 50,
      paths: ['forge/test/store.test.mjs'],
      deps: ['task-store'],
      spec: {
        files: { 'forge/test/store.test.mjs': 'test/store.test.mjs' },
        run: ['--test', 'forge/test/store.test.mjs'],
        repairTaskId: 'task-store',
      },
    },
    {
      id: 'task-service',
      title: 'Write Pulse application service',
      kind: 'write',
      priority: 40,
      paths: ['forge/src/service.mjs'],
      deps: ['task-store-test'],
      spec: { files: { 'forge/src/service.mjs': 'src/service.mjs' } },
    },
    {
      id: 'task-service-test',
      title: 'Verify service updates',
      kind: 'test',
      priority: 60,
      paths: ['forge/test/service.test.mjs'],
      deps: ['task-service', 'task-store-test'],
      spec: {
        files: { 'forge/test/service.test.mjs': 'test/service.test.mjs' },
        run: ['--test', 'forge/test/service.test.mjs'],
      },
    },
    {
      id: 'task-http',
      title: 'Expose Pulse HTTP API',
      kind: 'write',
      priority: 70,
      paths: ['forge/src/http.mjs'],
      deps: ['task-service'],
      spec: { files: { 'forge/src/http.mjs': 'src/http.mjs' } },
    },
    {
      id: 'task-cli',
      title: 'Expose Pulse CLI',
      kind: 'write',
      priority: 70,
      paths: ['forge/src/cli.mjs'],
      deps: ['task-service'],
      spec: { files: { 'forge/src/cli.mjs': 'src/cli.mjs' } },
    },
    {
      id: 'task-web',
      title: 'Publish Pulse status page',
      kind: 'write',
      priority: 80,
      paths: ['forge/web/index.html'],
      deps: ['task-http'],
      spec: { files: { 'forge/web/index.html': 'web/index.html' } },
    },
    {
      id: 'task-handoff',
      title: 'Write the session handoff',
      kind: 'handoff',
      priority: 90,
      paths: ['forge/HANDOFF.md'],
      deps: ['task-domain-test', 'task-store-test', 'task-service-test', 'task-cli', 'task-web'],
      spec: {},
    },
  ];
}
