export function planPulse() {
  return [
    {
      id: 'task-scaffold',
      title: 'Scaffold the Pulse package',
      kind: 'write',
      priority: 10,
      paths: ['forge/package.json', 'forge/README.md'],
      deps: [],
      spec: { files: { 'forge/package.json': 'package.json', 'forge/README.md': 'README.md' } },
    },
    {
      id: 'task-analysis',
      title: 'Analyze Pulse goals and risks',
      kind: 'analyze',
      priority: 15,
      paths: ['forge/ANALYSIS.md'],
      deps: [],
      spec: { files: { 'forge/ANALYSIS.md': 'ANALYSIS.md' } },
    },
    {
      id: 'task-domain',
      title: 'Write Pulse domain rules',
      kind: 'write',
      priority: 20,
      paths: ['forge/src/domain.mjs'],
      deps: [],
      spec: { files: { 'forge/src/domain.mjs': 'src/domain.mjs' } },
    },
    {
      id: 'task-domain-test',
      title: 'Verify domain invariants',
      kind: 'test',
      priority: 30,
      paths: ['forge/test/domain.test.mjs'],
      deps: ['task-domain'],
      spec: {
        files: { 'forge/test/domain.test.mjs': 'test/domain.test.mjs' },
        run: ['--test', 'forge/test/domain.test.mjs'],
      },
    },
    {
      id: 'task-store',
      title: 'Write durable Pulse store',
      kind: 'write',
      priority: 40,
      paths: ['forge/src/store.mjs'],
      deps: ['task-domain'],
      spec: {
        files: { 'forge/src/store.mjs': 'src/store.mjs' },
        buggyFiles: { 'forge/src/store.mjs': 'src/store.buggy.mjs' },
        buggyUntilAttempt: 1,
      },
    },
    {
      id: 'task-store-test',
      title: 'Verify store persistence',
      kind: 'test',
      priority: 50,
      paths: ['forge/test/store.test.mjs'],
      deps: ['task-store'],
      spec: {
        files: { 'forge/test/store.test.mjs': 'test/store.test.mjs' },
        run: ['--test', 'forge/test/store.test.mjs'],
        repairTaskId: 'task-store',
      },
    },
    {
      id: 'task-service',
      title: 'Write Pulse application service',
      kind: 'write',
      priority: 40,
      paths: ['forge/src/service.mjs'],
      deps: ['task-store-test'],
      spec: { files: { 'forge/src/service.mjs': 'src/service.mjs' } },
    },
    {
      id: 'task-service-test',
      title: 'Verify service updates',
      kind: 'test',
      priority: 60,
      paths: ['forge/test/service.test.mjs'],
      deps: ['task-service', 'task-store-test'],
      spec: {
        files: { 'forge/test/service.test.mjs': 'test/service.test.mjs' },
        run: ['--test', 'forge/test/service.test.mjs'],
      },
    },
    {
      id: 'task-http',
      title: 'Expose Pulse HTTP API',
      kind: 'write',
      priority: 70,
      paths: ['forge/src/http.mjs'],
      deps: ['task-service'],
      spec: { files: { 'forge/src/http.mjs': 'src/http.mjs' } },
    },
    {
      id: 'task-cli',
      title: 'Expose Pulse CLI',
      kind: 'write',
      priority: 70,
      paths: ['forge/src/cli.mjs'],
      deps: ['task-service'],
      spec: { files: { 'forge/src/cli.mjs': 'src/cli.mjs' } },
    },
    {
      id: 'task-web',
      title: 'Publish Pulse status page',
      kind: 'write',
      priority: 80,
      paths: ['forge/web/index.html'],
      deps: ['task-http'],
      spec: { files: { 'forge/web/index.html': 'web/index.html' } },
    },
    {
      id: 'task-security',
      title: 'Audit Pulse CLI and HTTP for fail-closed input',
      kind: 'security',
      priority: 85,
      paths: ['forge/SECURITY.md'],
      deps: ['task-http', 'task-cli'],
      spec: { files: { 'forge/SECURITY.md': 'SECURITY.md' } },
    },
    {
      id: 'task-review',
      title: 'Independent review of Pulse domain and persistence',
      kind: 'review',
      priority: 86,
      paths: ['forge/REVIEW.md'],
      deps: ['task-domain-test', 'task-store-test', 'task-service-test'],
      spec: { files: { 'forge/REVIEW.md': 'REVIEW.md' } },
    },
    {
      id: 'task-handoff',
      title: 'Write the session handoff',
      kind: 'handoff',
      priority: 90,
      paths: ['forge/HANDOFF.md'],
      deps: ['task-analysis', 'task-domain-test', 'task-store-test', 'task-service-test', 'task-cli', 'task-web', 'task-security', 'task-review'],
      spec: {},
    },
  ];
}

export function planContinuations(state) {
  const existing = new Set((state.tasks ?? []).map((task) => task.id));
  const succeeded = new Set((state.tasks ?? []).filter((task) => task.status === 'succeeded').map((task) => task.id));
  if (!succeeded.has('task-handoff')) return [];
  const next = [
    {
      id: 'task-memory-digest',
      title: 'Write product memory from swarm lessons',
      kind: 'digest',
      priority: 100,
      paths: ['forge/MEMORY.md'],
      deps: ['task-handoff'],
      spec: {},
    },
    {
      id: 'task-changelog',
      title: 'Record what the swarm learned in the changelog',
      kind: 'write',
      priority: 110,
      paths: ['forge/CHANGELOG.md'],
      deps: ['task-handoff'],
      spec: { files: { 'forge/CHANGELOG.md': 'CHANGELOG.md' } },
    },
    {
      id: 'task-metrics',
      title: 'Add Pulse risk metrics',
      kind: 'write',
      priority: 120,
      paths: ['forge/src/metrics.mjs'],
      deps: ['task-handoff'],
      spec: { files: { 'forge/src/metrics.mjs': 'src/metrics.mjs' } },
    },
    {
      id: 'task-metrics-test',
      title: 'Verify Pulse risk metrics',
      kind: 'test',
      priority: 130,
      paths: ['forge/test/metrics.test.mjs'],
      deps: ['task-metrics'],
      spec: {
        files: { 'forge/test/metrics.test.mjs': 'test/metrics.test.mjs' },
        run: ['--test', 'forge/test/metrics.test.mjs'],
      },
    },
  ];
  return next.filter((task) => !existing.has(task.id));
}
